### ISSUE TITLE
v50 Compatibility

### ISSUE THREAD

**Issue by niraqw** [sfDesat/Celestial-Tint#10]
I tried to play with the new LethalLevelLoader update for v50, but the space outside the ship is just black.

![20240423192932_1](https://github.com/sfDesat/Celestial-Tint/assets/22210045/d296a95e-b2dd-4816-b326-e2156a456a89)

BepInExPack v5.4.2100
Celestial_Tint v1.1.12
FixPluginTypesSerialization v1.1.1
HookGenPatcher v0.0.5
LethalLevelLoader v1.2.0
LethalLib v0.15.1
LethalModDataLib v1.2.2
ShipWindows v2.0.5

**Comment by Hurrynd** [comment]
![Lethal Company Celestial Tint](https://github.com/sfDesat/Celestial-Tint/assets/40642360/7222c3da-da1c-49d0-afbe-6f0a934a3685)


On my case it's happening as well. But I can see (if I'm inside the ship) a small moons outside. If I disable the mod and let Ship Windows only, I can see those moons (darkened, btw) as well as the space image. But Celestial Tint is pitch black. This didn't happen on v49 so perhaps it is a compatibility issue(?)

**Comment by sfDesat** [comment]
This should be fixed as of v1.2.0
