### ISSUE TITLE
Mod spamming errors

### ISSUE THREAD

**Issue by Test-Account666** [sfDesat/Celestial-Tint#11]
This mod is awesome, but the broken inside-ship light and the error spam currently prevent me from using it...

This is the error:
`Cascade Shadow atlasing has failed, only one directional light can cast shadows at a time`

See [Issue #3](https://github.com/sfDesat/Celestial-Tint/issues/3) for the broken inside-ship light.

**Comment by sfDesat** [comment]
Do you have other mods that add things in space?

**Comment by Test-Account666** [comment]
Actually, yes.

I had `SpaceSunShine` installed.

I disabled the light this mod adds and now it no longer spams errors.

The inside-ship light is still very wanky though
