### ISSUE TITLE
[Error  : Unity Log] NullReferenceException (when u second time hosting the game)

### ISSUE THREAD

**Issue by CoolLKKPS** [sfDesat/Celestial-Tint#17]
[Error  : Unity Log] NullReferenceException
Stack trace:
CelestialTintLoader.Terminal_Start_Postfix () (at <661a8bf312d44ef3a6c1e109827e5491>:IL_008D)
(wrapper dynamic-method) Terminal.DMD<Terminal::Start>(Terminal)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<Terminal::Start>?1666256914(Terminal)
LethalLib.Modules.Enemies.Terminal_Start (On.Terminal+orig_Start orig, Terminal self) (at <7fedbde26c084fb2af96612740f0c4ca>:IL_0350)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Terminal::Start>?-1249301900(Terminal)

**Comment by CoolLKKPS** [comment]
@sfDesat

**Comment by sfDesat** [comment]
fixed in the next update

**Comment by CoolLKKPS** [comment]
@sfDesat i still didn't see the update, but additional, conflict with LobbyControl

**Comment by sfDesat** [comment]
I forgot to push the update to thunderstore, it whould be updated now

**Comment by CoolLKKPS** [comment]
maybe u want to test with v55, here's the modpack for u, conflict with LobbyControl - load savefile function
Link: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h
