### ISSUE TITLE
If the cabin door is allowed to be opened while the ship is in orbit, it may cause some bugs in v56.

### ISSUE THREAD

**Issue by NakiriFox** [sfDesat/Celestial-Tint#21]
If the player turns off the magnet switch, the cruiser will fall out and this save will no longer be able to purchase cruiser without mod (More Cruiser).

When you play with strangers, you can't guarantee that they won't do it.

**Comment by BlueAntVR** [comment]
A workaround for now is you can install the MagnetLock mod which prevents using the magnet while in orbit. [https://thunderstore.io/c/lethal-company/p/DarthLilo/MagnetLock/](url)

**Comment by NakiriFox** [comment]
Yes, I noticed it before, but I forgot to close this issue ：）
