### ISSUE TITLE
[Compatability] SpaceSunShine

### ISSUE THREAD

**Issue by CatsArmy** [sfDesat/Celestial-Tint#4]
I believe my latest update to SpaceSunShine should have fixed the incompatibility. 
sorry for the late update on the compatibility status i thought i had already posted this issue but i guess i didn't.

the only thing i am not doing is auto detecting this mod and disabling my feature so yeah. you can mess with my configs if you need to for the full compatibility between the mods.

**Comment by sfDesat** [comment]
That is great! I will change the description of my mod. Sorry for the late response.

**Comment by CatsArmy** [comment]
> That is great! I will change the description of my mod. Sorry for the late response. 

Ay don worry about it we all are busy it's fine it's not like most people read the TS page of mods lol

**Comment by sfDesat** [comment]
Thats very true lol
