### ISSUE TITLE
Screen Freezes

### ISSUE THREAD

**Issue by FenixWCode** [sfDesat/Celestial-Tint#5]
I experienced screen freezes every 4-5 secs and after some testing i realized it only happens with this mod enabled.. If i disable it everything is fine again, here is my profile code if you try to recreate the issue. 018e544c-78f9-4897-718d-7cbdc637eaca

**Comment by sfDesat** [comment]
should be fixed in the latest update

**Comment by FenixWCode** [comment]
I tested it and the stutters still exist..

**Comment by sfDesat** [comment]
Ok it should be fixed now for real (v1.1.6
