### ISSUE TITLE
Doessa mod worksi fully clientsidedy?

### ISSUE THREAD

**Issue by Flloppis** [sfDesat/Celestial-Tint#6]
Amma tryin' ta joinsii servers with thissa and it keeps onna sayin' Error Occured-
![image](https://github.com/sfDesat/Celestial-Tint/assets/157853816/7b85500a-c385-4f42-9efa-0ffa7b5f7bc2)
![image](https://github.com/sfDesat/Celestial-Tint/assets/157853816/4a858301-3ef9-4aee-8d39-7b510c3dd030)

**Comment by AbandonedAccount1111** [comment]
@Flloppis yeah it does, but the issue is LethalLevelLoader that is not client-side and is doing networked checks, which is breaking the vanilla support.

**Comment by Flloppis** [comment]
Ooohh- O,O
Issa therey way ta make ittt vanilla compatibless?

**Comment by AbandonedAccount1111** [comment]
> Ooohh- O,O Issa therey way ta make ittt vanilla compatibless?

i already notified the maker on the discord, he's working on it.

**Comment by Flloppis** [comment]
Ooo!!! Yipiii !! Thanksii yerss! :>
